# Generated by Django 3.0.6 on 2020-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newsalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='selection',
            field=models.CharField(choices=[('Vegetation Localization', 'Vegetation Localization'), ('Crop Identification', 'Crop Identification'), ('Land Use', 'Land Use'), ('Perimeter', 'Perimeter')], default='Crop Identification', max_length=50),
        ),
    ]
