# Generated by Django 3.0.3 on 2020-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200506_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
