# Generated by Django 3.0.3 on 2020-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200508_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='selection',
            field=models.CharField(choices=[('Vegetation Localization', 'Vegetation Localization'), ('Object Detection', 'Object Detection'), ('Land Use', 'Land Use'), ('Parameter', 'Parameter')], default='Crop Identification', max_length=50),
        ),
    ]
